#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Aug  8 13:46:02 2019

@author: lianghao
"""

# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# Data PreProcessing
dataset = pd.read_csv("Ads_CTR_Optimisation.csv")

# Implementing UCB

# number of ads
import math
N = 10000
d = 10
numbers_of_selections = [0] * d
sums_of_selections = [0] * d
ads_selected = []
total_reward = 0

for round in range(0,N):
    max_upper_bound = 0
    best_ad = 0
    for ads in range(0,d):
        if numbers_of_selections[ads] > 0:
            average_reward = sums_of_selections[ads] / numbers_of_selections[ads]
            delta_ads = math.sqrt(3/2 * math.log(round+1) / numbers_of_selections[ads])
            upper_bound = average_reward + delta_ads
        else:
            upper_bound = 1e400
        if upper_bound > max_upper_bound:
            max_upper_bound = upper_bound
            best_ad = ads
    ads_selected.append(best_ad)
    reward = dataset.values[round, best_ad]
    numbers_of_selections[best_ad] = numbers_of_selections[best_ad] + 1
    sums_of_selections[best_ad] = sums_of_selections[best_ad] + reward
    total_reward = total_reward + reward

# Visualising the results
plt.hist(ads_selected)
plt.title('Histogram of ads selections')
plt.xlabel('Ads')
plt.ylabel('Number of times each ad was selected')
plt.show()
